### ISSUE TITLE
Dealer.reset() doesn't update button position correctly

### ISSUE THREAD

**Issue by uli-weltersbach** [fschlatt/clubs#4]
Hi @fschlatt,

First of all, thanks for taking the time to write this library and making it public!

I think [line 267 of engine.py](https://github.com/fschlatt/clubs/blob/master/clubs/poker/engine.py#L267) is missing a parenthesis around the `self.button + 1` part of the assignment operation:
```
self.button = self.button + 1 % self.num_players
```
vs.
```
self.button = (self.button + 1) % self.num_players
```

I can create a pull request with tests etc. if you'd like, but simply entering a REPL session should give you the proof.
E.g. a game with 3 players, button is on player 3 (index 2) and should be moved to player 1 (index 0) when `Dealer.reset()` is called:
```
>>> 2 + 1 % 3   
3 
```
vs.
```
>>> (2 + 1) % 3  
0  
```

**Comment by fschlatt** [comment]
Hey @uli-weltersbach ,

thanks for showing interest in my little pet project and for finding the bug. You are completely right. I've fixed the bug, added a test for it and created a new pypi release. It should therefore be fixed if you upgrade your package with `pip install -U clubs`.

**Comment by fschlatt** [comment]
Hey @uli-weltersbach ,

thanks for showing interest in my little pet project and for finding the bug. You are completely right. I've fixed the bug, added a test for it and created a new pypi release. It should therefore be fixed if you upgrade your package with `pip install -U clubs`.
